name: bybike
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  intl: ^0.19.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  # firebase_core: ^2.30.0
  # firebase_auth: ^4.19.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.4
  connectivity_plus: ^5.0.2
  image_picker: ^1.0.7
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  flutter_rating_bar: ^4.0.1
  pinput: ^4.0.0
  google_fonts: ^4.0.4
  flutter_facebook_auth: ^6.0.4
  google_sign_in: 6.1.5
#  flutter_google_places: ^0.3.0
#  google_maps_webservice: ^0.0.19
  google_api_headers: ^1.3.0
  awesome_snackbar_content: ^0.1.0
  geocoding: ^3.0.0
  flutter_typeahead: ^5.2.0
  google_search_place: ^0.0.4
  flutter_polyline_points: ^2.0.0
  google_maps_places_autocomplete_widgets: ^1.2.2
  uuid: ^4.2.2
  email_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Arial Rounded MT
      fonts:
        - asset: assets/fonts/ARIALROUNDEDMT.TTF

    - family: Pristina
      fonts:
        - asset: assets/fonts/PRISTINA.TTF

    - family: Sakkal Majalla
      fonts:
        - asset: assets/fonts/majalla.ttf
          style: italic

    - family: Agency FB
      fonts:
        - asset: assets/fonts/AgencyFB-Bold.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
      
    - family: Bahnschrift
      fonts:
        - asset: assets/fonts/BAHNSCHRIFT.TTF
      
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/segoe-ui.ttf
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
