// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdWNBKEkDtFQ5zVF20kR7xWUBkLuHSPuQ',
    appId: '1:414067748131:web:99741ea1b4ec6aa728b096',
    messagingSenderId: '414067748131',
    projectId: 'bybike-ffefe',
    authDomain: 'bybike-ffefe.firebaseapp.com',
    storageBucket: 'bybike-ffefe.appspot.com',
    measurementId: 'G-5NG80LBSJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPSEx1yHGv-66K0llHTx6IlLAHf0501jM',
    appId: '1:414067748131:android:31f330a25e4680ad28b096',
    messagingSenderId: '414067748131',
    projectId: 'bybike-ffefe',
    storageBucket: 'bybike-ffefe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfkn_7WsTrbvg_pfF5aXQ4eGr-K8iobEM',
    appId: '1:414067748131:ios:603b7a79e9e92c3428b096',
    messagingSenderId: '414067748131',
    projectId: 'bybike-ffefe',
    storageBucket: 'bybike-ffefe.appspot.com',
    androidClientId: '414067748131-0rcagi6jkg850o4sljgkcsc59segf2u8.apps.googleusercontent.com',
    iosClientId: '414067748131-mdstg12hger852jehqo0f2dit97q6vmh.apps.googleusercontent.com',
    iosBundleId: 'com.rides.bybike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfkn_7WsTrbvg_pfF5aXQ4eGr-K8iobEM',
    appId: '1:414067748131:ios:603b7a79e9e92c3428b096',
    messagingSenderId: '414067748131',
    projectId: 'bybike-ffefe',
    storageBucket: 'bybike-ffefe.appspot.com',
    androidClientId: '414067748131-0rcagi6jkg850o4sljgkcsc59segf2u8.apps.googleusercontent.com',
    iosClientId: '414067748131-mdstg12hger852jehqo0f2dit97q6vmh.apps.googleusercontent.com',
    iosBundleId: 'com.rides.bybike',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdWNBKEkDtFQ5zVF20kR7xWUBkLuHSPuQ',
    appId: '1:414067748131:web:8362195a3e83324328b096',
    messagingSenderId: '414067748131',
    projectId: 'bybike-ffefe',
    authDomain: 'bybike-ffefe.firebaseapp.com',
    storageBucket: 'bybike-ffefe.appspot.com',
    measurementId: 'G-E0GBNQ2BQZ',
  );
}
